### PR TITLE
R2312 foss acceptance criteria

### PR DESCRIPTION
**Pull request by kelaja**
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [X] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [X] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files -> not required, kindly see discussion.

### CODE REVIEW

**Comment by kelaja** [comment]
Hi @FaGru3n 

the FOSS Templates are ready for review, kindly check :)
-[X] MD Lint
-[X] Wording adapted
-[ ] Catena-X occurrences in TRACTUS-X

Best Regards,
Kelaja

**Comment by FaGru3n** [comment]
Hi @kelaja 
at the moment the only thing from myside would be a source file for the "other path" png as mermaid maybe also like the "happy paht"

**Comment by kelaja** [comment]
@FaGru3n okay, mermaid chart done 👍🏼
Can you accept the PR?
Thanks for the support

**Comment by FaGru3n** [comment]
> @FaGru3n okay, mermaid chart done 👍🏼 Can you accept the PR? Thanks for the support

and deleting the old file. 😉

**Review by FaGru3n — APPROVED** [review]
LGTM

**Pull request merged**
