### PR TITLE
feat: add pagination support for listing repos

### LINKED ISSUE #41: Add pagination support for getting all repos from the tractus-x organization
## Description

Currently, the checks dashboard gets the first 100 repos of the organization.
In order to be future proof we should use pagination to retrieve all available repos.

## Impact

Minor, just tidying up things and learning go.

## Additional information 

- [x] I'm willing to contribute to this feature

### PR DESCRIPTION
**Pull request by netomi**
## Description

This PR fixes #41. 

It adds pagination support for retrieving the list of repos of the organization.
Additionally it cleans up the temp directory created for cloning a repo.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by netomi** [comment]
The failed workflow run seems to be a known issue of the actions/checkout workflow with a recent release:

https://github.com/actions/checkout/issues/1448

**Review by SebastianBezold — APPROVED** [review]

**Comment by SebastianBezold** [comment]
Hey @netomi,

thanks a lot for this contribution! Was definitely needed. 
The lazy "just take 100, we don't have more right now" really wasn't a sustainable solution :)

**Comment by SebastianBezold** [comment]
> The failed workflow run seems to be a known issue of the actions/checkout workflow with a recent release:
> 
> [actions/checkout#1448](https://github.com/actions/checkout/issues/1448)
> 
> 130 thumbs up after 24 minutes :-)
> 
> Second re-run made it work.

Yes we experienced this in other repos as well

**Comment by netomi** [comment]
I am surprise that the otherwise great go-github library does not have pagination support out of the box. There are some ideas floating around which I took as inspiration, but having to do that yourself for every api that potentially only returns paged results is certainly a pain.

**Pull request merged**
