### PR TITLE
docs: move wiki content into repo + add links to general starting pages

### PR DESCRIPTION
**Pull request by FaGru3n**
## Description
- add [wiki](https://github.com/eclipse-tractusx/sig-release/wiki) content into the repo `sig-release` itself as discussed in [Office Hour Open Discussion](https://catenax-ng.github.io/blog#open-discussions)
- add links into the `README.md` to reference the specific documentation
- add legal notice for documentation based on [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07/#documentation)

fixes eclipse-tractusx/sig-infra#328

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by mabige** [comment]
Regarding: https://github.com/eclipse-tractusx/sig-release/wiki/PI11-Planning-CX-ART-Consortia

This Wiki described the Consortia CX ART planning activities within Tractus-X / Github for PI11 specifically.
It was dedicated to CX ART Consortia PI11 Planning at TX. 

Just removing "CX ART" Keywords from title and content will not be sufficient, since this Wiki does not describe the TX Open Planning activities generally. Also is this document describing an event which is in the past.

Recommendation: Delete Wiki page PI11-Planning-CX-ART-Consortia
Create a new Wiki or MD that describes TX Open Planning from scratch.

FYI: @stephanbcbauer

**Comment by FaGru3n** [comment]
> Regarding: https://github.com/eclipse-tractusx/sig-release/wiki/PI11-Planning-CX-ART-Consortia

> Just removing "CX ART" Keywords from title and content will not be sufficient, since this Wiki does not describe the TX Open Planning activities generally. Also is this document describing an event which is in the past.
> 
> Recommendation: Delete Wiki page PI11-Planning-CX-ART-Consortia Create a new Wiki or MD that describes TX Open Planning from scratch.

Deleting the  Wiki page PI11-Planning-CX-ART-Consortia i my plan afterwards to this PR... i want to first move the current state without the reference to CX-Art and named it `PI11-Planning.md` where the process is still described.

And if then furter information needed we can add this with new pull-requests on our desire.

**Comment by SebastianBezold** [comment]
HI @mabige,

good points. Back when we started the open planning discussions, I added a basic process description to the [top level README.md](https://github.com/eclipse-tractusx/sig-release/blob/main/README.md). I think it was enhanced since then. Do you think the current version matches our process? Do we need to link it in other places, so it's easier to find?

**Comment by mabige** [comment]
... let's have a quick call

**Comment by FaGru3n** [comment]
hi [chore: delete docs/PI11-Planning.md](https://github.com/eclipse-tractusx/sig-release/pull/354/commits/e6802350e3dffe00889ec103c4c63f15ea773352)

removed markdown file in the pr, so only 2 markdown files will moved.

Please review, thanks in advance.

**Review by SebastianBezold — APPROVED** [review]

**Pull request merged**
