### PR TITLE
feat: k8s notifier

### PR DESCRIPTION
**Pull request by tomaszbarwicki**
PR to add Kubernetes release notification. Feature enhances existing 'release notifier' tool which currently supports PostgreSQL release notification. Added specific k8s notification email template content as well as renamed and updated release notifier GitHub Actions workflow for automation.

Updates https://github.com/eclipse-tractusx/sig-infra/issues/320

### CODE REVIEW

**Review by FaGru3n — DISMISSED** [review]
LGTM but can not verify go section

**Review by FaGru3n — DISMISSED** [review]
LGTM

**Review by SebastianBezold — COMMENTED** [review]
I would love to see some automated test for the implementation.
It also seems, like we would send out emails for fix versions.
Looking at the history on the kubernetes release page, it seems like the release is always updated to the latest patch version.

does colly guarantee a correct order for onHTML? The used tag + css class combination is used a lot on that page

**Comment by tomaszbarwicki** [comment]
> I would love to see some automated test for the implementation. It also seems, like we would send out emails for fix versions. Looking at the history on the kubernetes release page, it seems like the release is always updated to the latest patch version.
> 
> does colly guarantee a correct order for onHTML? The used tag + css class combination is used a lot on that page

Added a basic unit test to verify returned release version is SemVer. Can't think of any other test, feel free to drop any suggestions. 
Couldn't find any prove that colly guarantees the order for onHTML hence implemented own order assurance using semver lib. 
Included as well in the email content link to step by step guide how to turn off the workflow if there are any issues.

**Comment by SebastianBezold** [comment]
> > I would love to see some automated test for the implementation. It also seems, like we would send out emails for fix versions. Looking at the history on the kubernetes release page, it seems like the release is always updated to the latest patch version.
> > does colly guarantee a correct order for onHTML? The used tag + css class combination is used a lot on that page
> 
> Added a basic unit test to verify returned release version is SemVer. Can't think of any other test, feel free to drop any suggestions. Couldn't find any prove that colly guarantees the order for onHTML hence implemented own order assurance using semver lib. Included as well in the email content link to step by step guide how to turn off the workflow if there are any issues.

There is plenty of things that can be tested. For example:
- notification only sent, if there is actually a new version
- New version get's persisted, if there is one
- Sent email contains references to new and old versions

**Comment by SebastianBezold** [comment]
Hi @tomaszbarwicki,

If you could resolve the merge conflict, then I'll approve the changes

**Comment by tomaszbarwicki** [comment]
> Hi @tomaszbarwicki,
> 
> If you could resolve the merge conflict, then I'll approve the changes

@SebastianBezold done

**Review by SebastianBezold — APPROVED** [review]

**Pull request merged**
