### PR TITLE
feat: add issue template suggest new kit

### PR DESCRIPTION
**Pull request by LuisRickert**
---
name: Request New KIT Template 
title: feat/add issue template to request new kit
---

## Description

With this Pull Request we add an Issue Template to request a new KIT. The Template consists of a questionnaire that collects the basic information about the new KIT. After raising an issue with this template, the community should review it and decide if the KIT should be added to the community project.

### CODE REVIEW

**Comment by FaGru3n** [comment]
@LuisRickert did you signed the eca on elipcse Tractus-X

**Comment by almadigabor** [comment]
> @LuisRickert did you signed the eca on elipcse Tractus-X

The ECA check passed.

**Comment by RolaH1t** [comment]
@FaGru3n after several discussions (e.g. with @danielmiehle) I can confirm, that we will "park" the idea of an additional/separate RePo for KITs for the moment. Please work with @kelaja to process all release-relevant issues for KITs also within the SIG Release RePo. We will review the idea towards the and of PI10, once initial learnings can be applied.

**Comment by RolaH1t** [comment]
@LuisRickert please dismiss this PullRequest. @danielmiehle will also confirm here, that the initial idea of a template to request a new KIT shall not be used for the time being. Thx, Roland

**Pull request closed without merging**
